name: nullable
description: Nullable setters in dart. Just forget about ifs with null for setting some value!
version: 0.1.0
homepage: https://github.com/fpdart/nullable
author: FPDart Team <shindakioku@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: ^1.0.0
